maidsafe/safe-mobile-browser

- SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetch.cs
> Update webfetch path parsing logic

- SafeMobileBrowser/SafeMobileBrowser/ViewModels/HomePageViewModel.cs
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
> strip url schema from address bar

- SafeMobileBrowser/SafeMobileBrowser/ViewModels/MenuPopUpViewModel.cs
> Fix share Activity in iOS

- SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewRenderer.cs
- SafeMobileBrowser/SafeMobileBrowser/AssetFiles/index.html
Fixes: #143 
- Add a zooming in and out feature for android (iOS already exists)
- disable zoom in home page
> Feature: zooming in and out 

- SafeMobileBrowser/SafeMobileBrowser.iOS/AppDelegate.cs
- SafeMobileBrowser/SafeMobileBrowser.iOS/Info.plist
- SafeMobileBrowser/SafeMobileBrowser/App.xaml.cs
- SafeMobileBrowser/SafeMobileBrowser/Helpers/MessageCenterConstants.cs
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
fixes: #9 
This PR adds the feature to directly open the `safe://` websites from any other app on iOS.
_**Note:** Android still pending._
> feat/iOS: open safe url in browser

- SafeMobileBrowser/SafeMobileBrowser.iOS/PlatformServices/PlatformService.cs
> fix(SafariViewController): Get rootviewcontroller to open links

- SafeMobileBrowser/SafeMobileBrowser.iOS/Info.plist
> enable landscape mode in iOS

- SafeMobileBrowser/SafeMobileBrowser/App.xaml
- SafeMobileBrowser/SafeMobileBrowser/Helpers/Constants.cs
- SafeMobileBrowser/SafeMobileBrowser/Helpers/ErrorConstants.cs
- SafeMobileBrowser/SafeMobileBrowser/Helpers/FileHelper.cs
- SafeMobileBrowser/SafeMobileBrowser/Models/IconFont.cs
- SafeMobileBrowser/SafeMobileBrowser/SafeMobileBrowser.csproj
- SafeMobileBrowser/SafeMobileBrowser/ViewModels/LogsModalPageViewModel.cs
- SafeMobileBrowser/SafeMobileBrowser/ViewModels/SettingsModalPageViewModel.cs
- SafeMobileBrowser/SafeMobileBrowser/Views/LogsModalPage.xaml
- SafeMobileBrowser/SafeMobileBrowser/Views/LogsModalPage.xaml.cs
- SafeMobileBrowser/SafeMobileBrowser/Views/SettingsModalPage.xaml
fixes: #167 
**Changes:**
- Add options on the settings page to get the list of log files
- Add logs page
- Show the list of log files
- Delete/Copy content of one file from the list
- Delete all log files (except the active one) from the navigation bar
> feat(log viewer): Add feature to copy/delete log files from settings page

- SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewClient.cs
- SafeMobileBrowser/SafeMobileBrowser/Helpers/Constants.cs
- SafeMobileBrowser/SafeMobileBrowser/ViewModels/HomePageViewModel.cs
fixes: #169 
A very hacky fix.
> fix/browser: fix loading of numeric websites 

- SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetch.cs
> fix (numeric url): load pages which have numeric public name and no service name

- SafeMobileBrowser.UITests/AppInitializer.cs
- SafeMobileBrowser.UITests/SafeMobileBrowser.UITests.csproj
- SafeMobileBrowser.UITests/Tests.cs
- SafeMobileBrowser.sln
- SafeMobileBrowser/SafeMobileBrowser.iOS/AppDelegate.cs
- SafeMobileBrowser/SafeMobileBrowser.iOS/SafeMobileBrowser.iOS.csproj
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml
- SafeMobileBrowser/SafeMobileBrowser/Views/MenuPopUp.xaml
fixes: #189 
Setups up the SAFEMobileBrowser.UITests Project
> Xamarin UI Test Setup

- SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewClient.cs
- SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewRenderer.cs
- SafeMobileBrowser/SafeMobileBrowser/Controls/HybridWebView.cs
- SafeMobileBrowser/SafeMobileBrowser/Models/IconFont.cs
- SafeMobileBrowser/SafeMobileBrowser/Models/WebFetchResponse.cs
- SafeMobileBrowser/SafeMobileBrowser/Models/WebsiteList.cs
- SafeMobileBrowser/SafeMobileBrowser/ViewModels/HomePageViewModel.cs
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
- SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetch.cs
> Update web fetch logic and UI to move between versions

- SafeMobileBrowser/SafeMobileBrowser.Android/MainActivity.cs
- SafeMobileBrowser/SafeMobileBrowser.Android/MediaDownload/FileHelper.cs
- SafeMobileBrowser/SafeMobileBrowser.Android/MediaDownload/ImageDownloader.cs
- SafeMobileBrowser/SafeMobileBrowser.Android/Properties/AndroidManifest.xml
- SafeMobileBrowser/SafeMobileBrowser.Android/SafeMobileBrowser.Android.csproj
- SafeMobileBrowser/SafeMobileBrowser.iOS/AppDelegate.cs
- SafeMobileBrowser/SafeMobileBrowser.iOS/SafeMobileBrowser.iOS.csproj
- SafeMobileBrowser/SafeMobileBrowser/SafeMobileBrowser.csproj
fixes: #201 
_**Note:** iOS testing pending_
> Update packages and target Android 10

- SafeMobileBrowser/SafeMobileBrowser.iOS/ControlRenderers/HybridWebViewRenderer.cs
- SafeMobileBrowser/SafeMobileBrowser.iOS/ControlRenderers/SafeSchemaHandler.cs
- SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetch.cs
**Changes:**
- Updated native webview renderer to show latest and current page version.
- Removed some commented code.
> feat(pWeb Controls): update pWeb controls on iOS and back forward

- SafeMobileBrowser/SafeMobileBrowser.Android/ControlRenderers/HybridWebViewClient.cs
- SafeMobileBrowser/SafeMobileBrowser.Android/SafeMobileBrowser.Android.csproj
- SafeMobileBrowser/SafeMobileBrowser.iOS/SafeMobileBrowser.iOS.csproj
- SafeMobileBrowser/SafeMobileBrowser/AssetFiles/FilesContainer.html
- SafeMobileBrowser/SafeMobileBrowser/Helpers/FileHelper.cs
- SafeMobileBrowser/SafeMobileBrowser/SafeMobileBrowser.csproj
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
- SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetch.cs
- SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetchService.cs
**Other changes:**
- Use a single App.AppSession objects everywhere to fetch the content so that re-authenticator updates are the Session references.
> Show files list when files container doesn't contain an index.html file

- SafeMobileBrowser/SafeMobileBrowser/AssetFiles/index.html
- SafeMobileBrowser/SafeMobileBrowser/ViewModels/HomePageViewModel.cs
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
> fix/pWeb: hide version change pages when static page

- SafeMobileBrowser/SafeMobileBrowser/App.xaml.cs
- SafeMobileBrowser/SafeMobileBrowser/Services/AuthenticationService.cs
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
> fix/iOS: fix authentication dialog cycle

- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
> fix/iOS: fix address bar animation fix

- SafeMobileBrowser/SafeMobileBrowser/App.xaml.cs
- SafeMobileBrowser/SafeMobileBrowser/Helpers/MessageCenterConstants.cs
- SafeMobileBrowser/SafeMobileBrowser/Services/AuthenticationService.cs
- SafeMobileBrowser/SafeMobileBrowser/Themes/DarkTheme.xaml
- SafeMobileBrowser/SafeMobileBrowser/Themes/LightTheme.xaml
- SafeMobileBrowser/SafeMobileBrowser/ViewModels/HomePageViewModel.cs
- SafeMobileBrowser/SafeMobileBrowser/ViewModels/MenuPopUpViewModel.cs
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml
- SafeMobileBrowser/SafeMobileBrowser/Views/HomePage.xaml.cs
- SafeMobileBrowser/SafeMobileBrowser/Views/LogsModalPage.xaml
- SafeMobileBrowser/SafeMobileBrowser/Views/MenuPopUp.xaml
Fixes: #239 
**Changes:**
- Added authentication icon in the top bar
- Icon uses green color to show if app is already authenticated otherwise a dark slate gray icon is shown.
**Pending:**
- The UI icons + colors aren't finalized yet.
> Show authentication icon in top bar

- README.md
- SafeMobileBrowser/SafeMobileBrowser/Helpers/Constants.cs
> chore/docs: update README and fix FAQ link

- SafeMobileBrowser/SafeMobileBrowser/Helpers/Constants.cs
- SafeMobileBrowser/SafeMobileBrowser/Helpers/ErrorConstants.cs
- SafeMobileBrowser/SafeMobileBrowser/Services/AuthenticationService.cs
- SafeMobileBrowser/SafeMobileBrowser/ViewModels/HomePageViewModel.cs
> Shared section download and connection error dialog improvements 

- SafeMobileBrowser/SafeMobileBrowser/AssetFiles/FilesContainer.html
- SafeMobileBrowser/SafeMobileBrowser/WebFetchImplementation/WebFetch.cs
fixes: #260 
**iOS**
**Android**
> feat/filescontainer: show file links when fetching a files container
